# Generated by Django 4.2.2 on 2023-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_creator_event_competitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2023-06-06'),
            preserve_default=False,
        ),
    ]
