# Generated by Django 4.2.2 on 2023-07-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['added']},
        ),
    ]
