# Generated by Django 4.2.2 on 2023-07-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
    ]
