# Generated by Django 4.2.2 on 2023-07-06 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_description_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(max_length=3500, validators=[django.core.validators.MinLengthValidator(3, message='Story description must be at least 3 characters!')]),
        ),
    ]
